"""
Django settings for heulisticai project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qbemp15goxw#ft!_$k6kyywn-0sx*^ps_78gt2%&-oz1*_jf_t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'frontend'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'heulisticai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'frontend/build')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'heulisticai.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "frontend/build/static"),
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
#STATICFILES_STORAGE = 'storages.backends.s3boto3.S3StaticStorage'


# AWS Credentials for access

AWS_ACCESS_KEY_ID = "AKIAVO6DXTXPKPQHJ463"

AWS_SECRET_ACCESS_KEY = "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"

AWS_STORAGE_BUCKET_NAME = "heulistic-content-img-vids"

AWS_QUERYSTRING_AUTH = False

# Google API Key
GOOGLE_API_KEY = "AIzaSyCfFf984vGmELGWgX-M3mYNMr7m9abI_ks"

# Stripe test
STRIPE_PUBLISHABLE_KEY = 'pk_live_51N1APUASZB5G51Lq8MQIXhdxcqQw16JmCPCsRKXlcxKGz1sksSfDeIhcFeGhqGHq2aYYKhWklOSj94Aj3txnxECw00kyKCbTkN'

# Stripe test
STRIPE_PUBLISHABLE_KEY_TEST = 'pk_test_51N1APUASZB5G51LqlRpNSm745a9l7ltCN67KjbmNuxtO9NCQNOgyvmT7wH5Kn9g5aeBPfEh1voZhvv5wJmidyFZW000CBSsgTv'

# Real secret key
STRIPE_SECRET_KEY = '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'

# stripe test key
STRIPE_SECRET_KEY_TEST = 'sk_test_51N1APUASZB5G51LqOvDHdiMtuLCMCcE0c7JudOK6b8thJLaSz142O76PPeVYuObclzrnJxE8uzqnek2a69p8Lsd300GaotQJn2'